//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeRentManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property_Table
    {
        public int Id { get; set; }
        public string Sellername { get; set; }
        public string Houseno { get; set; }
        public string Streetname { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public long Zip { get; set; }
        public string Flattype { get; set; }
        public long Rent { get; set; }
        public long Phone { get; set; }
        public string Email { get; set; }
        public string Description { get; set; }
        public byte[] Images { get; set; }
    }
}
